### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jaylac2000** [FAXES/DiscordVehicleWhitelist#4]
add a config option weather or not the vehicle deletes.

if set to true it will delete and send the restricted error message

if false it wont delete the vehicle but will still send the error message saying they cant drive it

this would make it helpful and wont leave cops stranded because some dude without permission got in their cars driver seat

**Comment by FAXES** [comment]
Sorry for the long delay with this one ahaha. I've had some spare time to implement this into an alpha version which is out. Once feedback has been obtained then it will be pushed to a stable release once verified.
